name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "bonjour je t'appelle de la pipeline"
      - run: ls -la
      - name: Check out repository code
        uses: actions/checkout@v4
 
